kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: monitoring
  name: grafana-storage
spec:
  storageClassName: do-block-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
