apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jitsi
  labels:
    k8s-app: jibri
  name: jibri
spec:
  selector:
      matchLabels:
        shard: "0"
  template:
    spec:
      # avoid that pods of different shards share zone
      nodeSelector:
        topology.kubernetes.io/zone: ZONE_2
      containers:
        - name: jibri
          env:
            - name: XMPP_SERVER
              value: shard-0-prosody
