apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: jitsi
  labels:
    k8s-app: jibri
  name: jibri
spec:
  selector:
    matchLabels:
      shard: "0"
  template:
    spec:
      # avoid that pods of different shards share zone
      nodeSelector:
        topology.kubernetes.io/zone: ZONE_1
      volumes:
        - name: jibri-recorder
          persistentVolumeClaim:
            claimName: jibri-recorder
      containers:
        - name: jibri
          env:
            - name: XMPP_SERVER
              value: shard-0-prosody
    metadata:
      labels:
        shard: "0"
