kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: jitsi
  name: jibri-recorder
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
