apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: jitsi
  labels:
    k8s-app: jibri
  name: jibri
spec:
  serviceName: jibri
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      k8s-app: jibri
      shard: "0"
  template:
    metadata:
      labels:
        k8s-app: jibri
        shard: "0"
    spec:
      nodeSelector:
        server-size: large
      initContainers:
        - name: init-set
          image: xuxant/init-container
          command: 
            - /tmp/copyfile.sh
          volumeMounts:
            - name: home-dir
              mountPath: /home/jibri
      containers:
        - name: jibri
          image: docker.io/jitsi/jibri
          resources:
            limits:
              memory: 4000Mi
              cpu: 2500m
            requests:
              memory: 2000Mi
              cpu: 1000m
          env:
            - name: XMPP_SERVER
              value: conference.lyon.com.ph
            - name: XMPP_DOMAIN
              value: conference.lyon.com.ph
            - name: XMPP_AUTH_DOMAIN
              value: auth.conference.lyon.com.ph
            - name: XMPP_INTERNAL_MUC_DOMAIN
              value: internal.auth.conference.lyon.com.ph
            - name: XMPP_RECORDER_DOMAIN
              value: recorder.conference.lyon.com.ph
            - name: TZ
              value: Asia/Manila
            - name: JIBRI_XMPP_USER
              value: jibri
            - name: JIBRI_XMPP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JIBRI_XMPP_PASSWORD
            - name: JIBRI_BREWERY_MUC
              value: JibriBrewery
            - name: JIBRI_RECORDER_USER
              value: recorder
            - name: JIBRI_RECORDER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: jitsi-config
                  key: JIBRI_RECORDER_PASSWORD
            - name: JIBRI_RECORDING_DIR
              value: /config/recordings
            - name: JIBRI_FINALIZE_RECORDING_SCRIPT_PATH
              value: /config/finalize.sh
            - name: JIBRI_STRIP_DOMAIN_JID
              value: conference.
            - name: JIBRI_LOGS_DIR
              value: /config/logs
            - name: DISPLAY
              value: :0
          volumeMounts:
            - name: jibri
              mountPath: '/etc/resolv.conf'
              subPath: resolv.conf
              readOnly: false
            - name: jibri
              mountPath: /config/finalize.sh
              subPath: finalize.sh
            - name: jibri-recorder
              mountPath: /config/recordings
            - name: jibri-logs
              mountPath: /config/logs
            - name: snd
              mountPath: /dev/snd
            - name: shm
              mountPath: /dev/shm
            - name: home-dir
              mountPath: /home/jibri
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_BIND_SERVICE
                - SYS_ADMIN
      volumes:
        - name: jibri
          configMap:
            name: jibri
            items:
              - key: resolv.conf
                path: resolv.conf
              - key: finalize.sh
                path: finalize.sh
        - name: jibri-logs
          emptyDir: {}
        - name: snd
          hostPath:
            path: /dev/snd
        - name: home-dir
          emptyDir: {}
        - name: asoundrc
          configMap:
            name: assound-1
            defaultMode: 0644
        - name: shm
          hostPath:
            path: /dev/shm
