apiVersion: v1
kind: Service
metadata:
  namespace: jitsi
  labels:
    service: jibri
  name: jibri
spec:
  selector:
    k8s-app: jibri
    shard: "0"
  ports:
  - name: "2222"
    port: 2222
    targetPort: 2222
  - name: "3333"
    port: 3333
    targetPort: 3333