apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: k8s
  namespace: monitoring
spec:
  retention: 7d
  resources:
    requests:
      memory: 1000Mi
      cpu: 250m
    limits:
      memory: 1000Mi
      cpu: 500m
  storage:
    volumeClaimTemplate:
      metadata:
        name: prometheus
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: rook-cephfs
        resources:
          requests:
            storage: 15Gi
