apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: haproxy-ingress
  namespace: jitsi
spec:
  tls:
  - hosts:
    # fill in host here
    - conference.lyon.ph
    secretName: jitsi-messenger-lyon-tls
